Wrong variable called for json output file
When using the json output option, it uses the wrong variable name, causing:
AttributeError: 'Values' object has no attribute 'output'